<a href="https://colab.research.google.com/github/ManeswarSahu11/PyTorch/blob/main/tensors_opsss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch= torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
mytorch=my_torch.view(2,5)
mytorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
mytorch2=my_torch.reshape(5,-1)
mytorch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [9]:
mytorch2[:]

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [10]:




mytorch2[:2]

tensor([[0, 1],
        [2, 3]])

In [11]:
mytorch2[:3]

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [12]:
mytorch2[::]

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [13]:
mytorch2[3:]

tensor([[6, 7],
        [8, 9]])

In [14]:
mytorch2[1:]

tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [15]:
mytorch2[:1]

tensor([[0, 1]])

In [ ]:
mytorch2=my_torch.reshape(5,-1)
mytorch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
mytorch2[:]

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [21]:




mytorch2[:2,]

tensor([[0, 1],
        [2, 3]])

In [ ]:
mytorch2[:3]

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
mytorch2[::]

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [20]:
mytorch2[3,:]

tensor([6, 7])

In [19]:
mytorch2[:,1:]

IndexError: too many indices for tensor of dimension 2

In [17]:
mytorch2[:1]

tensor([[0, 1]])